on: push

env:
  clientId: 27dfc9fe-a781-49c1-af38-ae3863dd06cf
  tenant: wk2c.onmicrosoft.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Replace Action
      uses: datamonsters/replace-action@v2
      with:
        files: '*.xml'
        replacements: yourtenant.=wk2c.
    - name: 'Upload TrustFrameworkBase Policy'
      uses: azure-ad-b2c/deploy-trustframework-policy@v3
      with:
        folder: "./SocialAndLocalAccountsWithMfa/"
        files: "TrustFrameworkBase.xml,TrustFrameworkExtensions.xml,SignUpOrSignin.xml"
        tenant: ${{ env.tenant }}
        clientId: ${{ env.clientId }}
        clientSecret: ${{ secrets.AADB2C_WK2C_SECRET }}
